/**
 * lectures.js — Content data for all 10 lectures of Module I.3
 * QM Programme · Quantum Dynamics, Perturbation Theory, and Physical Systems
 *
 * Each entry drives one generated .pptx file via the per-lecture generators
 * in src/generate-LXX.js.
 */

const lectures = [
  {
    code: "L01", num: 1,
    title: "Pure/Mixed States and the Density Matrix",
    subtitle: "§2.3–2.5 — Density Operator Formalism",
    track: "Sakurai ↔ Dirac Dual-Track — Lecture 1",
    pacing: [
      "0–20 min: Motivation — why a single ket is insufficient for sub-systems or ensembles",
      "20–45 min: Mixed states: ρ̂ = Σᵢ pᵢ|ψᵢ⟩⟨ψᵢ|; classical vs. quantum uncertainty",
      "45–70 min: Properties of ρ̂: Hermiticity, unit trace, positivity; purity γ = Tr(ρ̂²)",
      "70–90 min: Bipartite systems; partial trace ρ̂_A = Tr_B(ρ̂_AB); entanglement entropy preview",
    ],
    outcomes: [
      "Construct ρ̂ for pure states, statistical mixtures, and subsystems of composite systems",
      "Verify the three defining properties (ρ̂† = ρ̂, Tr(ρ̂) = 1, ρ̂ ≥ 0) for given matrices",
      "Compute expectation values ⟨Â⟩ = Tr(ρ̂Â) and purity; distinguish pure from mixed states",
      "Apply the partial trace to obtain reduced density matrices and compute entanglement entropy",
    ],
    tiers: {
      hs:    "Classical probability analogy: coin-flip vs. genuine quantum superposition; Bloch sphere intuition",
      begug: "Compute ρ̂, Tr(ρ̂²), and ⟨Â⟩ for 2×2 examples; verify properties numerically",
      advug: "Prove Tr(ρ̂²) ≤ 1 via spectral decomposition; Bloch vector parameterisation; partial trace",
      msc:   "Purification of mixed states; Schmidt decomposition; entanglement entropy and sub-additivity",
      phd:   "Trace-class operators in ∞ dimensions; von Neumann entropy; quantum relative entropy; CP maps preview",
    },
    assessment: {
      setA: "Construct ρ̂ for explicit mixtures; compute purity and ⟨σ̂_z⟩; partial trace for 2-qubit Bell states",
      setB: "Prove Tr(ρ̂²) ≤ (Tr ρ̂)² with equality iff rank-1; show entanglement entropy vanishes for product states",
    },
    prev: "I.2 — L12: Tensor Products, Spin & Density Operators (intro)",
    next: "L02 — Bases: Discrete and Continuous",
    keyFormulas: [
      "ρ̂ = |ψ⟩⟨ψ|  (pure state)",
      "ρ̂ = Σᵢ pᵢ |ψᵢ⟩⟨ψᵢ|  (mixture)",
      "⟨Â⟩ = Tr(ρ̂ Â)  (expectation value)",
      "γ = Tr(ρ̂²) ≤ 1  (purity)",
      "ρ̂_A = Tr_B(ρ̂_AB)  (partial trace)",
      "S = −Tr(ρ̂_A ln ρ̂_A)  (entanglement entropy)",
    ],
    concepts: [
      "Why is ρ̂ needed when a ket |ψ⟩ is insufficient?",
      "What is the physical difference between a coherent superposition and a classical mixture?",
      "State the three mathematical properties that every density operator must satisfy.",
      "True/False: A state with purity γ = 0.5 is a pure state. Justify.",
      "How does the partial trace 'discard' information about subsystem B?",
      "True/False: Entanglement entropy is zero for a product state. Justify.",
      "When does ⟨Â⟩ = Tr(ρ̂Â) reduce to the usual ⟨ψ|Â|ψ⟩?",
      "Compare the Bloch sphere representation of a pure vs. mixed spin-½ state.",
    ],
  },
  {
    code: "L02", num: 2,
    title: "Bases: Discrete and Continuous",
    subtitle: "Resolution of Identity · Wavefunctions · Fourier Transform",
    track: "Computational ↔ Mathematical Dual-Track — Lecture 2",
    pacing: [
      "0–20 min: Discrete ONB; ⟨eᵢ|eⱼ⟩ = δᵢⱼ; Î = Σᵢ|eᵢ⟩⟨eᵢ|; basis changes via unitary matrices",
      "20–45 min: Continuous bases: x̂|x⟩ = x|x⟩; ⟨x|x'⟩ = δ(x−x'); Î = ∫dx|x⟩⟨x|; ψ(x) = ⟨x|ψ⟩",
      "45–70 min: Momentum representation ψ̃(p) = ⟨p|ψ⟩; ⟨x|p⟩ = e^{ipx/ℏ}/√(2πℏ); Fourier transform",
      "70–90 min: Dirac delta distribution: properties, Fourier representation; over-completeness preview",
    ],
    outcomes: [
      "Use the resolution of identity in discrete and continuous forms to evaluate any bracket",
      "Derive the wavefunction ψ(x) = ⟨x|ψ⟩ as a projection onto the position basis",
      "Perform basis changes between position and momentum representations via Fourier transforms",
      "Manipulate delta functions and understand their distributional nature",
    ],
    tiers: {
      hs:    "'Snapshots' in different languages — why ψ(x) is just one way to describe the same state",
      begug: "Compute ψ(x) from a discrete-basis ket; evaluate simple Fourier transforms; use δ-function properties",
      advug: "Prove Parseval–Plancherel from completeness; handle δ(x) carefully in operator matrix elements",
      msc:   "Distribution theory; generalised eigenvectors; Fourier transform as unitary map on L²(ℝ)",
      phd:   "Gel'fand triple Φ ⊂ L² ⊂ Φ'; nuclear spectral theorem; coherent states and frame theory",
    },
    assessment: {
      setA: "Compute ψ(x) and ψ̃(p) for Gaussian and square-well states; evaluate ⟨x|p̂|ψ⟩ via completeness",
      setB: "Prove Fourier transform is unitary on L²; delta-function identities and distributional derivatives",
    },
    prev: "L01 — Pure/Mixed States and the Density Matrix",
    next: "L03 — Uncertainty and Commutation Relations",
    keyFormulas: [
      "Î = Σᵢ |eᵢ⟩⟨eᵢ|  (discrete completeness)",
      "Î = ∫dx |x⟩⟨x|  (continuous completeness)",
      "ψ(x) = ⟨x|ψ⟩  (wavefunction as projection)",
      "⟨x|p⟩ = e^{ipx/ℏ}/√(2πℏ)  (position-momentum overlap)",
      "ψ̃(p) = ∫ e^{−ipx/ℏ}/√(2πℏ) ψ(x)dx  (Fourier transform)",
      "∫δ(x−x₀)f(x)dx = f(x₀)  (sifting property)",
    ],
    concepts: [
      "What is the resolution of identity and why is it called 'completeness'?",
      "True/False: ⟨x|x'⟩ = δ(x−x') means position eigenstates are normalisable. Justify.",
      "How is the Fourier transform a unitary change of basis?",
      "What is ψ(x) = ⟨x|ψ⟩ geometrically — what does it mean?",
      "True/False: The momentum eigenstate |p⟩ is square-integrable. Justify.",
      "Insert identity twice to convert ⟨x|Â²|ψ⟩ into position-space integrals.",
      "What is the Dirac delta distribution — not a function but a...?",
      "Compare discrete vs. continuous completeness relations. What fundamentally changes?",
    ],
  },
  {
    code: "L03", num: 3,
    title: "Uncertainty and Commutation Relations",
    subtitle: "Robertson Inequality · CSCO · Quantum Zeno Effect",
    track: "Physical ↔ Mathematical Dual-Track — Lecture 3",
    pacing: [
      "0–20 min: Commutators as algebraic fingerprint of incompatibility; [x̂,p̂] = iℏ; Jacobi identity",
      "20–45 min: Robertson inequality ΔA·ΔB ≥ ½|⟨[Â,B̂]⟩| derived via Cauchy–Schwarz; Schrödinger improvement",
      "45–65 min: CCRs [x̂ᵢ,p̂ⱼ] = iℏδᵢⱼ; Stone–von Neumann theorem (statement); CSCO and quantum numbers",
      "65–90 min: Compatible/incompatible measurements; projection postulate; sequential measurements; Zeno effect; ΔEΔt",
    ],
    outcomes: [
      "Derive Robertson's uncertainty inequality from the Cauchy–Schwarz inequality",
      "Evaluate commutators for polynomial functions of x̂ and p̂",
      "Define a complete set of commuting observables (CSCO) and explain how it labels states uniquely",
      "Distinguish compatible from incompatible observables and their measurement implications",
    ],
    tiers: {
      hs:    "'You cannot know both position and momentum exactly' — why it is NOT about clumsy measurements",
      begug: "Compute [x̂,p̂²], [x̂²,p̂] from CCR; evaluate ΔxΔp for a Gaussian wavepacket",
      advug: "Full derivation of Robertson inequality; saturation conditions; prove [Â,B̂]=0 ⟺ common eigenbasis",
      msc:   "Schrödinger's stronger uncertainty relation; CSCO for hydrogen; Stone–von Neumann theorem and its physics",
      phd:   "Weyl form of CCR; non-equivalent representations; quantum Zeno rigorously; entropic uncertainty relations",
    },
    assessment: {
      setA: "Evaluate commutators; compute variances for HO eigenstates; verify Robertson inequality numerically",
      setB: "Derive Robertson inequality from scratch; prove saturation condition; CSCO for 3D central potential",
    },
    prev: "L02 — Bases: Discrete and Continuous",
    next: "L04 — Infinitesimal Generators, Symmetries, and Noether's Theorem",
    keyFormulas: [
      "[x̂,p̂] = iℏ  (canonical commutation relation)",
      "(ΔA)² = ⟨Â²⟩ − ⟨Â⟩²  (variance)",
      "ΔA·ΔB ≥ ½|⟨[Â,B̂]⟩|  (Robertson inequality)",
      "Saturation: |δÂ|ψ⟩ = iλ|δB̂|ψ⟩ for real λ  (minimum uncertainty)",
      "[Â,B̂] = 0 ⟺ simultaneous eigenbasis exists  (compatibility)",
      "CSCO: {Â₁,Â₂,...} mutually commuting, labels states uniquely",
    ],
    concepts: [
      "Why does [Â,B̂] ≠ 0 imply that Â and B̂ cannot be simultaneously sharp?",
      "True/False: The uncertainty principle is a statement about measurement disturbance. Justify.",
      "State the Robertson inequality and identify when it is saturated.",
      "What is a CSCO and why does hydrogen need three quantum numbers (n,l,m)?",
      "True/False: If [Â,B̂] = 0, both operators share at least one common eigenvector. Justify.",
      "Explain the quantum Zeno effect in one sentence.",
      "Compute [x̂², p̂] using [x̂,p̂] = iℏ.",
      "What is the energy–time uncertainty relation and why is Δt not an operator?",
    ],
  },
  {
    code: "L04", num: 4,
    title: "Infinitesimal Generators, Symmetries, & Noether",
    subtitle: "Stone's Theorem · Conservation Laws · Discrete Symmetries",
    track: "Physical ↔ Mathematical Dual-Track — Lecture 4",
    pacing: [
      "0–20 min: One-parameter unitary groups Û(θ) = e^{iθĜ}; Stone's theorem; momentum, L̂, Ĥ as generators",
      "20–45 min: Symmetry of Ĥ: [Ĥ,Û]=0 ⟺ [Ĥ,Ĝ]=0; conservation of Ĝ in Heisenberg picture = Noether",
      "45–65 min: Discrete symmetries: parity Π̂, charge conjugation Ĉ, time reversal T̂ (anti-unitary); CPT theorem",
      "65–90 min: Symmetry breaking: explicit vs. spontaneous; degenerate ground states; Goldstone modes (qualitative)",
    ],
    outcomes: [
      "Identify the generator of a given one-parameter unitary group using Stone's theorem",
      "Prove Noether's theorem in quantum mechanics via the Heisenberg equation of motion",
      "Classify discrete symmetries and their representations (unitary vs. anti-unitary)",
      "Distinguish explicit from spontaneous symmetry breaking and describe physical consequences",
    ],
    tiers: {
      hs:    "'If physics looks the same after a transformation, something is conserved' — deepest symmetry principle",
      begug: "Verify [Ĥ,p̂]=0 for translationally invariant Ĥ; check parity of simple wavefunctions",
      advug: "Prove Noether's theorem from Heisenberg EOM; parity selection rules; show Π̂x̂Π̂⁻¹=−x̂",
      msc:   "Lie algebra generators; structure constants; su(2) algebra; full Wigner classification of discrete symmetries",
      phd:   "Projective representations; central extensions; spontaneous breaking and Goldstone; Wigner–Eckart preview",
    },
    assessment: {
      setA: "Identify generators for rotations/translations/phase shifts; verify conservation laws; parity of wavefunctions",
      setB: "Prove Noether's theorem in Heisenberg picture; classify H-atom symmetries; analyse CPT invariance",
    },
    prev: "L03 — Uncertainty and Commutation Relations",
    next: "L05 — Time Evolution I: Time-Independent Hamiltonians",
    keyFormulas: [
      "Û(θ) = e^{iθĜ}  (one-parameter unitary group)",
      "[Ĥ,Ĝ] = 0 ⟺ d⟨Ĝ⟩/dt = 0  (Noether's theorem)",
      "Π̂x̂Π̂⁻¹ = −x̂,  Π̂p̂Π̂⁻¹ = −p̂  (parity action)",
      "T̂ is anti-unitary: T̂(α|ψ⟩) = α*T̂|ψ⟩  (time reversal)",
      "Ĝ = −i dÛ/dθ|_{θ=0}  (Stone's theorem — generator)",
      "CPT is an exact symmetry of all local QFTs  (CPT theorem)",
    ],
    concepts: [
      "What does Stone's theorem guarantee about the generator of a unitary group?",
      "State Noether's theorem in quantum mechanics using the Heisenberg equation.",
      "True/False: Time reversal T̂ is a unitary symmetry. Justify.",
      "Why is momentum conservation linked to translation invariance?",
      "What distinguishes explicit symmetry breaking from spontaneous symmetry breaking?",
      "True/False: CPT is violated by the weak interaction. Justify.",
      "Give an example of a system with parity symmetry and one without.",
      "What are Goldstone modes and when do they appear?",
    ],
  },
  {
    code: "L05", num: 5,
    title: "Time Evolution I — Time-Independent Hamiltonians",
    subtitle: "Schrödinger Equation · Û(t) · Stationary States · Probability Current",
    track: "Wave-Mechanics ↔ Operator Dual-Track — Lecture 5",
    pacing: [
      "0–15 min: Time-evolution postulate iℏ∂_t|ψ(t)⟩ = Ĥ|ψ(t)⟩; linearity and unitarity requirements",
      "15–40 min: Time evolution operator Û(t,t₀): group property, unitarity; time-independent case Û(t)=e^{−iĤt/ℏ}",
      "40–65 min: Stationary states Ĥ|Eₙ⟩=Eₙ|Eₙ⟩; general solution; expectation values of time-independent operators",
      "65–90 min: Time-reversal anti-unitary T̂; Kramers degeneracy; probability current j; continuity equation",
    ],
    outcomes: [
      "Derive Û(t) = e^{−iĤt/ℏ} from the time-evolution postulate",
      "Evolve an arbitrary initial state by expanding in the energy eigenbasis",
      "Identify and exploit stationary state structure for computing expectation values",
      "Derive the probability current and continuity equation in position representation",
    ],
    tiers: {
      hs:    "'The Hamiltonian is the quantum engine of time evolution' — energy eigenstates oscillate simply",
      begug: "Evolve a two-level system; compute ⟨σ̂_z⟩(t); derive Rabi oscillation frequency",
      advug: "Full derivation of Û; probability current; prove unitarity of e^{−iĤt/ℏ} for Hermitian Ĥ",
      msc:   "Time-reversal symmetry; Kramers degeneracy proof for half-integer spin; Stone's theorem connection",
      phd:   "Stone's theorem and generator domain; self-adjoint extensions; Zeno paradox and its resolution",
    },
    assessment: {
      setA: "Evolve superposition states; compute ⟨Ê⟩(t), ⟨x̂⟩(t); derive probability current for plane waves",
      setB: "Prove group property of Û; unitarity; derive continuity equation; analyse Kramers degeneracy",
    },
    prev: "L04 — Generators, Symmetries, and Noether's Theorem",
    next: "L06 — Time Evolution II: Time-Dependent Hamiltonians",
    keyFormulas: [
      "iℏ ∂_t|ψ(t)⟩ = Ĥ|ψ(t)⟩  (TDSE)",
      "Û(t) = e^{−iĤt/ℏ}  (time-independent Ĥ)",
      "|ψ(t)⟩ = Σₙ cₙ e^{−iEₙt/ℏ} |Eₙ⟩  (general solution)",
      "j = (ℏ/2mi)(ψ*∇ψ − ψ∇ψ*)  (probability current)",
      "∂_t|ψ|² + ∇·j = 0  (continuity equation)",
      "Kramers: T̂²=−1 ⟹ at least 2-fold degeneracy",
    ],
    concepts: [
      "Why must the time-evolution operator be unitary?",
      "True/False: The energy expectation value changes with time for a stationary state. Justify.",
      "What is the group property of Û(t,t₀) and what does it imply physically?",
      "Derive the time derivative of ⟨Â⟩ for a time-independent operator Â.",
      "True/False: T̂ is a unitary operator. Justify (hint: T̂ involves complex conjugation).",
      "What is Kramers degeneracy and when does it occur?",
      "Write the continuity equation for probability density and identify each term.",
      "How does the position-space Schrödinger equation emerge from the abstract TDSE?",
    ],
  },
  {
    code: "L06", num: 6,
    title: "Time Evolution II — Time-Dependent Hamiltonians",
    subtitle: "Dyson Series · Magnus Expansion · Floquet Preview",
    track: "Physical ↔ Mathematical Dual-Track — Lecture 6",
    pacing: [
      "0–20 min: Failure of e^{−iĤt/ℏ} when [Ĥ(t₁),Ĥ(t₂)]≠0; integral equation; iterative solution",
      "20–45 min: Time-ordered exponential T exp(−i/ℏ ∫Ĥdt'); Dyson's T operator; first- and second-order terms",
      "45–65 min: Piecewise-constant approximation; product formula; Trotter–Suzuki and quantum simulation",
      "65–90 min: Magnus expansion Ω₁,Ω₂,...; unitarity preservation; convergence radius; driven spin-½; Berry phase preview",
    ],
    outcomes: [
      "Derive the Dyson series for a time-dependent Hamiltonian from the integral equation",
      "Write the time-ordered exponential and evaluate its first two terms explicitly",
      "Explain why the Magnus expansion preserves unitarity while the Dyson series does not term-by-term",
      "Apply the piecewise-constant approximation to a simple driven system",
    ],
    tiers: {
      hs:    "'When the Hamiltonian changes in time, the future depends on the full history' — spinning top analogy",
      begug: "First-order Dyson term; transition probability formula; numerical piecewise evolution for a qubit",
      advug: "Full Dyson series derivation; prove time-ordering is necessary; compute Ω₁ and Ω₂ of Magnus expansion",
      msc:   "Magnus convergence; Trotter–Suzuki product formula and its error; connection to quantum simulation circuits",
      phd:   "Magnus expansion in Lie algebraic language; Floquet theory for periodic Ĥ(t); geometric phases",
    },
    assessment: {
      setA: "Compute first-order Dyson term for oscillating Ĥ; piecewise evolution of a qubit; transition probability",
      setB: "Derive Dyson series from integral equation; prove Ω₁ of Magnus; convergence criterion application",
    },
    prev: "L05 — Time Evolution I: Time-Independent Hamiltonians",
    next: "L07 — Pictures of QM and the Heisenberg Picture",
    keyFormulas: [
      "Û = T exp(−i/ℏ ∫_{t₀}^{t} Ĥ(t')dt')  (Dyson / time-ordered)",
      "Û^{(1)} = −(i/ℏ) ∫Ĥ(t')dt'  (first Dyson term)",
      "Ω₁(t) = −i/ℏ ∫_{t₀}^{t} Ĥ(t')dt'  (first Magnus cumulant)",
      "Ω₂(t) = −1/2ℏ² ∫∫[Ĥ(t'),Ĥ(t'')]dt'dt''  (second cumulant)",
      "Û ≈ e^{Ω₁+Ω₂+...}  (Magnus — exactly unitary)",
      "Û_Trotter ≈ ∏ₖ e^{−iĤ(tₖ)Δt/ℏ}  (Trotter–Suzuki)",
    ],
    concepts: [
      "Why does e^{−iĤt/ℏ} fail when the Hamiltonian is time-dependent?",
      "What does the time-ordering operator T do to a product of operators?",
      "True/False: Each term in the Dyson series is individually unitary. Justify.",
      "Why does the Magnus expansion preserve unitarity term-by-term?",
      "What is the physical meaning of the first Magnus cumulant Ω₁?",
      "True/False: The Trotter product formula is exact for all step sizes Δt. Justify.",
      "State one physical context where time-dependent Hamiltonians are essential.",
      "How does the Magnus expansion connect to Floquet theory for periodic Ĥ(t)?",
    ],
  },
  {
    code: "L07", num: 7,
    title: "Pictures of QM and the Heisenberg Picture",
    subtitle: "Heisenberg EOM · Ehrenfest Theorem · Canonical Quantisation",
    track: "Physical ↔ Algebraic Dual-Track — Lecture 7",
    pacing: [
      "0–15 min: Picture equivalence — physical predictions are picture-independent; Schrödinger picture reviewed",
      "15–40 min: Heisenberg picture: Â_H(t)=Û†ÂÛ; static states; Heisenberg EOM d/dtÂ_H=(i/ℏ)[Ĥ,Â_H]+(∂_tÂ)_H",
      "40–65 min: Ehrenfest d⟨x̂⟩/dt=⟨p̂⟩/m; virial theorem; constants of motion [Ĥ,Â]=0⟹dÂ_H/dt=0",
      "65–90 min: Canonical quantisation: Poisson brackets → commutators; Dirac's rule; operator ordering ambiguities",
    ],
    outcomes: [
      "Transform operators and states between the Schrödinger and Heisenberg pictures",
      "Derive and apply the Heisenberg equation of motion",
      "Prove and use Ehrenfest's theorem and the virial theorem",
      "Apply Dirac's canonical quantisation rule and identify operator ordering issues",
    ],
    tiers: {
      hs:    "'In one picture the states move, in the other the clocks move' — active vs. passive view",
      begug: "Transform x̂(t) and p̂(t) for harmonic oscillator; verify Ehrenfest's theorem numerically",
      advug: "Full derivation of Heisenberg EOM; virial theorem proof; solve x̂_H(t) and p̂_H(t) for quadratic V",
      msc:   "Dirac quantisation rule; Weyl ordering; connection to classical integrability and action-angle variables",
      phd:   "Algebraic QM; Heisenberg picture in C*-algebra language; Moyal bracket and Wigner function",
    },
    assessment: {
      setA: "Solve Heisenberg EOM for HO; compute ⟨x̂⟩(t) and ⟨p̂⟩(t); verify Ehrenfest for cubic potential",
      setB: "Prove virial theorem; apply canonical quantisation to a classical system; ordering ambiguities for x̂²p̂",
    },
    prev: "L06 — Time Evolution II: Time-Dependent Hamiltonians",
    next: "L08 — The Dirac (Interaction) Picture",
    keyFormulas: [
      "Â_H(t) = Û†(t) Â_S Û(t)  (Heisenberg picture operator)",
      "dÂ_H/dt = (i/ℏ)[Ĥ,Â_H] + (∂_tÂ)_H  (Heisenberg EOM)",
      "d⟨x̂⟩/dt = ⟨p̂⟩/m  (Ehrenfest theorem I)",
      "d⟨p̂⟩/dt = −⟨∇V⟩  (Ehrenfest theorem II)",
      "{f,g}_PB → [f̂,ĝ]/(iℏ)  (Dirac's quantisation rule)",
      "2⟨T̂⟩ = ⟨x̂·∇V⟩  (virial theorem)",
    ],
    concepts: [
      "What is invariant across all pictures of quantum mechanics?",
      "Write the Heisenberg EOM for x̂_H(t) in a harmonic potential V = ½mω²x².",
      "True/False: The Heisenberg-picture state ket is time-dependent. Justify.",
      "State Ehrenfest's theorem and identify when it reduces to Newton's second law.",
      "What is the quantum analogue of a classical constant of motion?",
      "True/False: Canonical quantisation is unique — there is no ordering ambiguity. Justify.",
      "Compute x̂_H(t) for a free particle (V=0) using the Heisenberg EOM.",
      "What is the virial theorem and in what systems is it most useful?",
    ],
  },
  {
    code: "L08", num: 8,
    title: "The Dirac (Interaction) Picture",
    subtitle: "S-Matrix · Dyson Series in IP · Three-Picture Comparison",
    track: "Physical ↔ Mathematical Dual-Track — Lecture 8",
    pacing: [
      "0–15 min: Motivation: perturbative treatment of V̂(t) using exact Ĥ₀ dynamics; splitting Ĥ = Ĥ₀ + V̂(t)",
      "15–40 min: IP states |ψ_I(t)⟩=e^{iĤ₀t/ℏ}|ψ_S(t)⟩; operators V̂_I(t)=e^{iĤ₀t/ℏ}V̂e^{−iĤ₀t/ℏ}; IP Schrödinger eq.",
      "40–65 min: IP propagator Û_I(t,t₀); Dyson series in IP; perturbative transition amplitudes; Ŝ = Û_I(∞,−∞)",
      "65–90 min: Comparison table of all three pictures: states, operators, EOM, preferred use-cases",
    ],
    outcomes: [
      "Transform states and operators into and out of the interaction picture",
      "Derive the interaction picture Schrödinger equation from the full equation of motion",
      "Write the Dyson series in the interaction picture to any desired order",
      "Connect the S-matrix to the interaction picture propagator and physical scattering amplitudes",
    ],
    tiers: {
      hs:    "'Park the easy part in the operators; let the hard part drive the states' — practical bookkeeping",
      begug: "Transform V̂=λx̂ into IP for HO Ĥ₀; compute first-order Dyson term for simple perturbation",
      advug: "Full transformation procedure; Dyson series to second order; prove equivalence of all three pictures",
      msc:   "S-matrix and cross-sections; optical theorem; Lippmann–Schwinger preview; Feynman diagram structure",
      phd:   "S-matrix in QFT; adiabatic switching; Gell-Mann–Low theorem; LSZ reduction formula (conceptual)",
    },
    assessment: {
      setA: "Transform operators/states to IP; compute first-order transition amplitude for harmonic perturbation",
      setB: "Derive IP EOM; prove unitarity of S-matrix; second-order Dyson series for constant perturbation",
    },
    prev: "L07 — Pictures of QM and the Heisenberg Picture",
    next: "L09 — Perturbation Theory",
    keyFormulas: [
      "|ψ_I(t)⟩ = e^{iĤ₀t/ℏ}|ψ_S(t)⟩  (IP state)",
      "V̂_I(t) = e^{iĤ₀t/ℏ} V̂ e^{−iĤ₀t/ℏ}  (IP operator)",
      "iℏ∂_t|ψ_I⟩ = V̂_I(t)|ψ_I⟩  (IP Schrödinger equation)",
      "Û_I = T exp(−i/ℏ ∫V̂_I dt')  (IP propagator)",
      "Ŝ = Û_I(∞,−∞)  (S-matrix definition)",
      "⟨f|Ŝ|i⟩ = transition amplitude from i to f",
    ],
    concepts: [
      "What motivates splitting Ĥ = Ĥ₀ + V̂ in the interaction picture?",
      "True/False: In the interaction picture, both states and operators are time-dependent. Justify.",
      "How does the IP Schrödinger equation differ from the full Schrödinger equation?",
      "What is the S-matrix physically — what does it encode?",
      "True/False: The S-matrix is unitary if probability is conserved. Justify.",
      "Compare the three pictures: which quantity is time-dependent in each?",
      "Write the first-order term of the Dyson series in the interaction picture.",
      "What is the connection between the S-matrix and measurable cross-sections?",
    ],
  },
  {
    code: "L09", num: 9,
    title: "Perturbation Theory",
    subtitle: "RSPT · Degenerate PT · Variational Principle · Feynman–Hellmann",
    track: "Applied ↔ Formal Dual-Track — Lecture 9",
    pacing: [
      "0–20 min: Setup: Ĥ=Ĥ₀+λV̂; perturbative ansatz; non-degenerate case; convergence conditions",
      "20–45 min: RSPT: E_n^{(1)}=⟨n⁰|V̂|n⁰⟩; first-order state correction; second-order energy; breakdown",
      "45–65 min: Degenerate PT: degenerate subspace; block-diagonalise V̂; secular equation; correct zeroth-order states",
      "65–90 min: Feynman–Hellmann theorem; adiabatic theorem (statement); Ritz variational principle",
    ],
    outcomes: [
      "Derive first- and second-order energy corrections in non-degenerate RSPT",
      "Compute first-order state corrections and apply them to matrix elements",
      "Handle degenerate perturbation theory by diagonalising V̂ in the degenerate subspace",
      "Apply the Feynman–Hellmann theorem and the Ritz variational principle",
    ],
    tiers: {
      hs:    "'A small push changes energy levels slightly' — first-order PT as quantum Taylor expansion for energies",
      begug: "First-order energy corrections; linear Stark effect for hydrogen n=2 by diagonalisation",
      advug: "Second-order energy; convergence conditions; full degenerate PT procedure; Feynman–Hellmann proof",
      msc:   "Kato–Rellich theorem; Brillouin–Wigner PT; Born–Oppenheimer; adiabatic theorem proof sketch",
      phd:   "Resolvent formalism; Dyson equation for resolvent; divergence of PT series and resummation methods",
    },
    assessment: {
      setA: "First-order corrections for anharmonic oscillator λx̂⁴; linear and quadratic Stark effect; variational bound",
      setB: "Second-order energy for shifted HO; degenerate PT for n=2 hydrogen; Feynman–Hellmann for HO",
    },
    prev: "L08 — The Dirac (Interaction) Picture",
    next: "L10 — Time-Dependent PT, Open Systems, and Many-Body Preview",
    keyFormulas: [
      "Ĥ = Ĥ₀ + λV̂  (perturbation splitting)",
      "E_n^{(1)} = ⟨n⁰|V̂|n⁰⟩  (first-order energy correction)",
      "|n^{(1)}⟩ = Σ_{m≠n} ⟨m⁰|V̂|n⁰⟩/(E_n⁰−E_m⁰) |m⁰⟩  (first-order state)",
      "E_n^{(2)} = Σ_{m≠n} |⟨m⁰|V̂|n⁰⟩|²/(E_n⁰−E_m⁰)  (second-order energy)",
      "∂E_n/∂λ = ⟨n|∂Ĥ/∂λ|n⟩  (Feynman–Hellmann theorem)",
      "E₀ ≤ ⟨φ|Ĥ|φ⟩/⟨φ|φ⟩  (Ritz variational principle)",
    ],
    concepts: [
      "What is the expansion parameter λ in RSPT and when is the perturbation series valid?",
      "True/False: The first-order energy correction is always nonzero. Justify with a counter-example.",
      "Why does degenerate PT require diagonalising V̂ in the degenerate subspace first?",
      "State the Feynman–Hellmann theorem and give one physical application.",
      "True/False: The variational energy is always an overestimate of the ground-state energy. Justify.",
      "What breaks down in non-degenerate PT when two unperturbed levels are nearly degenerate?",
      "Write the secular equation for degenerate PT in a 2-fold degenerate subspace.",
      "How does the Born–Oppenheimer approximation use the adiabatic theorem?",
    ],
  },
  {
    code: "L10", num: 10,
    title: "TDPT, Open Systems, and Many-Body Preview",
    subtitle: "Fermi's Golden Rule · Lindblad Equation · Decoherence",
    track: "Applied ↔ Structural Dual-Track — Lecture 10",
    pacing: [
      "0–20 min: TDPT: first-order amplitude c_f^{(1)}(t); transition probability |c_f^{(1)}|²; sudden and adiabatic limits",
      "20–40 min: Fermi's golden rule: density of states ρ(Eᶠ); Γ_{i→f}=(2π/ℏ)|⟨f|V̂|i⟩|²ρ(Eᶠ); selection rules",
      "40–65 min: Open systems: Lindblad master equation; jump operators L̂_k; decay channels; dephasing",
      "65–90 min: Decoherence and pointer states; many-body preview: two-electron system, exchange, singlet/triplet",
    ],
    outcomes: [
      "Derive Fermi's golden rule from first-order time-dependent perturbation theory",
      "Write the Lindblad master equation and identify the physical role of each term",
      "Explain decoherence as environment-induced suppression of off-diagonal density matrix elements",
      "Construct two-electron spin states (singlet and triplet) and explain their exchange interaction origin",
    ],
    tiers: {
      hs:    "'Open systems as a leaky box' — energy and information escaping to environment; radioactive decay as Fermi's rule",
      begug: "Compute Γ_{i→f} for constant perturbation; simple Lindblad evolution (amplitude damping) for a qubit",
      advug: "Derive Fermi's golden rule; verify Lindblad preserves Tr(ρ̂)=1 and positivity; singlet/triplet construction",
      msc:   "GKSL theorem and complete positivity; Kraus representation; spin-boson model; Born–Markov approximation",
      phd:   "Nakajima–Zwanzig projection; non-Markovian dynamics; Floquet–Lindblad; entanglement in many-body systems",
    },
    assessment: {
      setA: "Compute Γ for atom in oscillating field; simple Lindblad evolution; singlet/triplet state construction",
      setB: "Derive Fermi's golden rule; prove Lindblad trace-preserving; exchange from antisymmetry of 2e wavefunction",
    },
    prev: "L09 — Perturbation Theory",
    next: "L11 — Example Systems and Physical Effects (Module I.3 finale)",
    keyFormulas: [
      "c_f^{(1)}(t) = −(i/ℏ)∫_{t₀}^t e^{iω_{fi}t'}⟨f|V̂(t')|i⟩dt'  (amplitude)",
      "Γ_{i→f} = (2π/ℏ)|⟨f|V̂|i⟩|²ρ(Eᶠ)  (Fermi's golden rule)",
      "ρ̂̇ = −(i/ℏ)[Ĥ,ρ̂] + Σ_k(L̂_k ρ̂ L̂_k† − ½{L̂_k†L̂_k, ρ̂})  (Lindblad)",
      "Pointer states: [Ĥ_env, |ptr⟩⟨ptr|] = 0  (environment selection)",
      "|S=0⟩ = (|↑↓⟩ − |↓↑⟩)/√2  (singlet — antisymmetric)",
      "|S=1,M=0⟩ = (|↑↓⟩ + |↓↑⟩)/√2  (triplet — symmetric)",
    ],
    concepts: [
      "From what approximation does Fermi's golden rule emerge and when is it valid?",
      "True/False: Fermi's golden rule applies only when the final state is discrete. Justify.",
      "What is the physical role of the jump operators L̂_k in the Lindblad equation?",
      "True/False: The Lindblad equation preserves the trace of the density matrix. Justify.",
      "Explain decoherence in one sentence without using the word 'collapse'.",
      "What is the exchange interaction and why does it arise from antisymmetry alone?",
      "True/False: A triplet spin state is symmetric under particle exchange. Justify.",
      "What is a pointer state and why is it selected by the environment?",
    ],
  },
];

module.exports = lectures;
