all: quantum_mechanics_syllabus.tex
	pdflatex quantum_mechanics_syllabus.tex
clean:
	rm -f quantum_mechanics_syllabus.aux
	rm -f quantum_mechanics_syllabus.log
	rm -f quantum_mechanics_syllabus.out
	rm -f quantum_mechanics_syllabus.pdf
	rm -f quantum_mechanics_syllabus.toc

